### PR TITLE
support for channel identification

### PR DESCRIPTION
**Pull request by r3-yamauchi**

### CODE REVIEW

**Comment by kibaffo33** [comment]
Hi @r3-yamauchi, testing your PR, it seems to add a new line for each word. Do you get the same results?

**Comment by r3-yamauchi** [comment]
I fixed sort order. and added sample file `"number_of_channels": 2`

**Comment by kibaffo33** [comment]
Hi @r3-yamauchi. Perhaps you see a different output, but when I ran your update I still got the following result:


Time | Speaker | Content
-- | -- | --
0.0 | ch_0 | Lorem
0.43 | ch_0 | Ipsum
0.51 | ch_0 | is
0.7 | ch_0 | simply
0.93 | ch_0 | dummy
1.05 | ch_0 | text
1.31 | ch_0 | of
1.72 | ch_0 | the
2.13 | ch_1 | Yeh
2.54 | ch_0 | printing
2.96 | ch_0 | and
3.08 | ch_0 | typesetting

I've done some work on it, up to a5481fe57a1482b8349a13adba16083a1b94a4df, and now it will look like this:

Time | Speaker | Content
-- | -- | --
0:00:00 | ch_0 | Lorem Ipsum is simply dummy text of the
0:00:02 | ch_1 | Yeh
0:00:02 | ch_0 | printing and typesetting

Your PR is now shown as merged, I'll update pypi soon.

Thanks for brining up channel identification.

**Comment by r3-yamauchi** [comment]
your refactoring is awesome!!!

`data["results"]["items"]` may not include `"start_time"` as in the example below.
to prevent `KeyError: 'start_time'`. ex: https://github.com/r3-yamauchi/aws_transcribe_to_docx/blob/6853a85069cb4e0a26ce9ff970f161d0dfd9ba25/tscribe/__init__.py#L209

```
            {
              "start_time": "47.76",
              "end_time": "47.93",
              "alternatives": [
                {
                  "confidence": "1.0",
                  "content": "ませ"
                }
              ],
              "type": "pronunciation"
            },
            {
              "alternatives": [
                {
                  "confidence": "0.0",
                  "content": "?"
                }
              ],
              "type": "punctuation"
            },
            {
              "start_time": "47.94",
              "end_time": "47.97",
              "alternatives": [
                {
                  "confidence": "0.9519",
                  "content": "ん"
                }
              ],
              "type": "pronunciation"
            },

**Comment by kibaffo33** [comment]
Ah, thanks for that, added in commit fdea60e36600378e8b71e40921b828c7e9f3b139. Nice use of the `continue` keyword.

**Comment by r3-yamauchi** [comment]
Thanks.  I will continue to use this wonderful tool !!

**Pull request merged**
